---
apiVersion: v1
kind: Task
metadata:
    name: aws-cli-s3-list
spec:
    containerImage: amazon/aws-cli
    mountDir: .
    workdir: .
    commandsSpec:
        - binary:
          commands:
              - ls -la
              - pwd
              - help
        - binary:
          commands:
              - s3 help
    envVarsSpec:
        envVarsScanned:
            scanAWSEnvVars:
                enabled: true
                failIfNotSet: false
                RemoveEnvVarsIfFound:
                    - AWS_SESSION_TOKEN
                    - AWS_SECURITY_TOKEN
                    - AWS_PROFILE_ID
                ignoreIfNotSetOrEmpty:
                    - AWS_SESSION_TOKEN
                    - AWS_SECURITY_TOKEN
                    - AWS_PROFILE_ID
                requiredEnvVars:
                    - AWS_ACCESS_KEY_ID
                    - AWS_SECRET_ACCESS_KEY
