---
apiVersion: v1
kind: Task
metadata:
    name: docker-dind
spec:
    containerImage: docker:stable-dind
    mountDir: examples
    workdir: aws-ecr-rust
    commandsSpec:
        - binary:
          commands:
              - ls -la
              - pwd
              - printenv
        - binary:
          commands:
              - docker build -t my-image .
