---
apiVersion: v1
kind: Task
metadata:
    name: iac-terragrunt
spec:
    containerImage: alpine/terragrunt
    mountDir: .
    workdir: examples/terragrunt
    commandsSpec:
        - binary:
          commands:
              - ls -ltrah /mnt
        - binary: terragrunt
          commands:
              - init
              - plan
              - apply -auto-approve
              - destroy -auto-approve
