---
apiVersion: v1
kind: Task
metadata:
    name: iac-terragrunt
spec:
    containerImage: alpine/terragrunt
    mountDir: .
    workdir: examples/terragrunt
    envVarsSpec:
        envVarsScanned:
            scanAWSEnvVars:
                enabled: true
                failIfNotSet: true
                removeEnvVarsIfFound:
                    - AWS_PROFILE
                    - AWS_SESSION_TOKEN
                    - AWS_SECURITY_TOKEN
                ignoreIfNotSetOrEmpty:
                    - AWS_SESSION_TOKEN
                    - AWS_SECURITY_TOKEN
                requiredEnvVars:
                    - AWS_ACCESS_KEY_ID
                    - AWS_SECRET_ACCESS_KEY
    commandsSpec:
        - binary:
          commands:
              - ls -ltrah /mnt
        - binary: terragrunt
          commands:
              - init
              - plan
              - apply -auto-approve
              - destroy -auto-approve
