---
apiVersion: v1
kind: Task
metadata:
    name: my-task
spec:
    containerImage: terragrunt
    workdir: /my/workdir
    mountDir: /my/rootdir
    baseDir: /my/basedir
    envVarsSpec:
        envVars:
            VAR1: value1
            VAR2: value2
        dotFiles:
            - .env.something
            - .env.another
        envVarsScanned:
            scanAWSEnvVars:
                enabled: true
                failIfNotSet: false
                removeEnvVarsIfFound:
                    - var1
                ignoreIfNotSetOrEmpty:
                    - var3
                    - var4
                requiredEnvVars:
                    - VAR1
                    - VAR2
            scanTerraformEnvVars:
                enabled: true
                failIfNotSet: false
                ignoreIfNotSetOrEmpty:
                    - var5
                    - var6
                requiredEnvVars:
                    - VAR1
                    - VAR2
            scanCustomEnvVars:
                - custom_var1
                - custom_var2
    commandsSpec:
        - binary: command1
          commands:
              - arg1
              - arg2
        - binary: command2
          commands:
              - arg1
              - arg2
