---
apiVersion: v1
kind: Task
metadata:
    name: my-task
spec:
    containerImage: terragrunt
    workdir: /my/workdir
    mountDir: /my/rootdir
    envVarsSpec:
        envVars:
            VAR1: value1
            VAR2: value2
        options:
            scanAWSEnvVars:
                - aws_var1
                - aws_var2
            scanTerraformEnvVars: true
            scanCustomEnvVars:
                - custom_var1
                - custom_var2
            dotFiles:
                - .env.something
                - .env.another
    commandsSpec:
        - binary: command1
          commands:
              - arg1
              - arg2
        - binary: command2
          commands:
              - arg1
              - arg2
