---
apiVersion: v1
kind: Task
metadata:
    name: node-js-inspect-version
spec:
    containerImage: node:alpine
    workdir: workflows
    mountDir: .github
    envVarsSpec:
#    envVars:
#      VAR1: value1
#      VAR2: value2
        options:
#      scanAWSEnvVars:
#        - AWS_ACCESS_KEY_ID
#        - AWS_SECRET_ACCESS_KEY
#      scanTerraformEnvVars: true
#      scanCustomEnvVars:
#        - custom_var1
#        - custom_var2
#      dotFiles:
#        - ../../.env.sandbox
#        - ../../.env.sandbox.pay
    commandsSpec:
        - binary:
          commands:
              - ls -la
              - pwd
        - binary: node
          commands:
              - --version
