---
name: Go Unit Test

on:
    push:
        branches:
            - '**'
    pull_request:
        paths:
            - '**.go'
env:
    GO_VERSION: ~1.20

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

            - name: Set up Go
              uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
              with:
                  go-version: ${{ env.GO_VERSION }}

            - name: Test
              run: |
                  go test ./... -v
