---
name: Go Unit Test

on:
    push:
        branches:
            - '**'
    pull_request:
        paths:
            - '**.go'

jobs:
    test:
        name: Run Go Unit Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20 # Adjust as per the latest version

            - name: Test
              run: |
                  go test ./... # Runs tests on all packages in the repository, adjust as per your test structure
