---
name: Run golangci-lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    golangci-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code into the Go module directory
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3

            - name: golangci-lint
              uses: reviewdog/action-golangci-lint@22adb9d08853436506154413f5683c2e749d3b85 # v2
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  reporter: github-pr-check
